config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  get "pages/about" => "pages#about", as: :about_page

  get "/location" => "application#location"

  resources :cuisines, only: [:new, :create]

  resources :ingredients, only: [:new, :create]

  get "business_places/owned" => "business_places#owned", as: :owned_business_places

  resources :business_places do
    resources :dishes, only: [:create, :edit, :update]
    resources :items, only: [:new, :create, :edit, :update]
  end

  post "items/copy" => "items#copy", as: :copy_items

  resources :dishes, only: [:destroy]
  resources :items, only: [:destroy]

  get "items/search" => "items#search", as: :search_items

  resources :roles, except: [:index, :show]

end

app/models/business_cuisine.rb
class BusinessCuisine < ActiveRecord::Base
  belongs_to :business_place
  belongs_to :cuisine

  validates :business_place, presence: true, uniqueness: { scope: :cuisine }
end

app/models/business_place.rb
class BusinessPlace < ActiveRecord::Base
  has_many :business_cuisines, dependent: :destroy
  belongs_to :cuisine
  has_many :cuisines, through: :business_cuisines
  has_many :business_place_users, dependent: :destroy
  has_many :users, through: :business_place_users
  has_many :dishes, dependent: :destroy
  has_many :items, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: [:address, :city] }
  validates :description, presence: true, length: { maximum: 35 }
  validates :address, presence: true
  validates :zip_code, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :phone_number, presence: true
  validates :cuisine, presence: true
  # validates :latitude, presence: true
  # validates :longitude, presence: true
  mount_uploader :cover_photo, PhotoUploader
  accepts_nested_attributes_for :cuisines

  geocoded_by :full_address
  after_validation :geocode, if: :full_address_changed?
  after_create :create_business_place_user

  attr_accessor :current_user

  def show_address
    "#{address}, #{city}"
  end

  def full_address
    "#{address}, #{zip_code} #{city} #{ISO3166::Country[country].name}"
  end

  def full_address_changed?
    address_changed? || zip_code_changed? || city_changed? || country_changed?
  end

  def create_business_place_user
    bpu = BusinessPlaceUser.new(business_place: self, user: current_user, main: true)
    bpu.save
  end

  def owner
    bpu = BusinessPlaceUser.where(business_place: self, main: true).first
    return bpu.user unless bpu.nil?
    return nil
  end

  def today_items
    self.items.where('start_datetime <= :start AND end_datetime >= :end', start: Date.today, end: Date.today + 1)
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  validates :name, presence: true, uniqueness: { scope: :state }
  validates :state, presence: true
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :business_cuisines
  has_and_belongs_to_many :business_places, through: :business_cuisines
  # has_many :business_places, through: :business_cuisine
  validates :name, presence: true, uniqueness: true
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :business_place
  has_many :items

  validates :name, length: { minimum: 3, maximum: 30 }
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, uniqueness: { scope: [:business_place] }
  validates :business_place, presence: true
  validates :description, presence: true
  validates :price, presence: true

  def today_items
    self.items.where('start_datetime >= :start AND end_datetime <= :end', start: Date.today, end: Date.today + 1)
  end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :item_info
  has_and_belongs_to_many :items, through: :item_info
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :dish
  belongs_to :business_place
  belongs_to :user
  has_many :item_info, dependent: :destroy
  has_many :ingredients, through: :item_info
  validates :name, length: { minimum: 3, maximum: 30 }
  mount_uploader :photo, PhotoUploader
  accepts_nested_attributes_for :ingredients

  validates :dish, presence: true
  validates :business_place, presence: true
  validates :user, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  attr_accessor :distance, :walking_time

end

app/models/item_info.rb
class ItemInfo < ActiveRecord::Base
  belongs_to :item
  belongs_to :ingredient

  validates :item, presence: true, uniqueness: { scope: :ingredient }
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
  validates :name, presence: true, uniqueness: { scope: :country }
  validates :country, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :business_place_users
  has_many :business_places, through: :business_place_users
  mount_uploader :photo, PhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, omniauth_providers: [:facebook]
  validates :email, presence: true, uniqueness: true




  def self.find_for_facebook_oauth(auth)
    # Rails version 5
    #   user_params = auth.to_h.slice(:provider, :uid)
    #   user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    #   user_params[:facebook_picture_url] = auth.info.image
    #   user_params[:token] = auth.credentials.token
    #   user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    #   user = User.where(provider: auth.provider, uid: auth.uid).first
    #   user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    #   if user
    #     user.update(user_params)
    #   else
    #     user = User.new(user_params)
    #     user.password = Devise.friendly_token[0,20]  # Fake password for validation
    #     user.save
    #   end

    #   return user
    # end

    # Rails 4.2.6 (wiki)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name   # assuming the user model has a name
      user.last_name = auth.info.last_name   # assuming the user model has a name
      user.facebook_picture_url = auth.info.image # assuming the user model has an image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
      user.confirmed_at = Time.now
    end
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
  validates :user_id, presence: true
  validates :role_id, presence: true, uniqueness: { scope: :user_id }
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/views/layouts/modal.html.erb
<% if content_for?(:modal_title) %>
  <div class="modal-header">
    <button type="button" class="close close-md" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><%= yield(:modal_title) %></h4>
  </div>
<% end %>
<div class="modal-body">
  <%= yield %>
</div>
<% if content_for?(:modal_footer) %>
  <%= yield(:modal_footer) %>
<% end %>

<%= yield(:after_js) %>

app/views/shared/_footer.html.erb
<div class="wrapper-footer">
  <div class="container-fluid no-margin no-padding">
    <div class="footer">
      <div class="row no-margin" style="padding: 15px;">
        <div class="col-xs-2 col-xs-offset-3 no-padding">
          <p class= "footer-link"><%= link_to "About", about_page_path, id: "about-link" %></p>
        </div>
        <div class="col-xs-2 no-padding" >
          <p class= "footer-link"><%= link_to "Contact", "#" %></p>
        </div>
        <div class="col-xs-2 no-padding">
          <p class= "footer-link"><%= link_to "Legal  ", "#" %></p>
        </div>
      </div>
      <hr>
      <div class="row no-margin" style="padding: 15px;">
        <div class="col-xs-4 col-xs-offset-4 no-padding">
          <p>
            <a href=""><i class="fa fa-instagram"></i></a>
            <a href=""><i class="fa fa-facebook"></i></a>
            <a href=""><i class="fa fa-twitter"></i></a>
          </p>
        </div>
        <div class="col-xs-4 no-padding">
          <p id="footer-about">© Fresh</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer_old.html.erb
  <div class="wrapper-yellow wrapper-yellow-no-margin" style="padding-top: 0px; padding-bottom: 10px;">
  <div class="footer">
    <!-- <div class="container"> -->

      <!-- <div class="row">
       <div class="col-xs-2 col-xs-offset-5">
        <div class="col-xs-4">
          <div class="footer-icon">
            <a href=""><i class="fa fa-facebook"></i></a>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="footer-icon">
            <a href=""><i class="fa fa-instagram"></i></a>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="footer-icon">
            <a href=""><i class="fa fa-twitter"></i></a>
          </div>
        </div>
      </div>
    </div> -->

<!--     <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="col-xs-4">
          <div class="footer-link">
            <%= link_to "About us", about_page_path %>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="footer-link">
            <%= link_to "Contact", "#" %>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="footer-link">
            <%= link_to "Privacy", "#" %>
          </div>
        </div>
      </div>
    </div>

    <hr>

    <div class="footer-icons">
      <a href=""><i class="fa fa-facebook"></i></a>
      <a href=""><i class="fa fa-instagram"></i></a>
      <a href=""><i class="fa fa-twitter"></i></a>
    </div>

    <div id="footer-about">© Fresh, Inc.</div>

  </div>
</div>
</div> -->

      <!-- <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <div class="row">
            <div class="col-xs-4">
              <div class="footer-link">
                <%= link_to "About us", about_page_path %>
              </div>
            </div>
            <div class="col-xs-4">
              <div class="footer-link">
                <%= link_to "Contact", "#" %>
              </div>
            </div>
            <div class="col-xs-4">
              <div class="footer-link">
                <%= link_to "Terms & Privacy", "#" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-icons">
      <a href=""><i class="fa fa-facebook"></i></a>
      <a href=""><i class="fa fa-instagram"></i></a>
      <a href=""><i class="fa fa-twitter"></i></a>
    </div>

    <div id="footer-about">© Fresh, Inc.</div> -->
    <div class="text-center">
      <ul class="list-layout list-inline" style="padding-top: 18px; padding-bottom: 0px;">
        <li><a href=""><i class="fa fa-facebook"></i></a></li>
        <li><a href=""><i class="fa fa-instagram"></i></a></li>
        <li><a href=""><i class="fa fa-twitter"></i></a></li>
      </ul>
    </div>
      <ul class="list-layout list-inline text-center" style="padding-top: 0px; padding-bottom: 6px; ">
          <li class="footer-link"><a href="#">About</a></li>
          <li class="footer-link"><a href="#">Contact</a></li>
          <li class="footer-link"><a href="#">Terms &amp; Privacy</a></li>
          <li class="footer-about">© Fresh</li>
      </ul>

<!--     <div class="footer-about hide-sm">© Fresh</div>
    </div> -->
  </div>
</div>

app/views/shared/_listcard.html.erb
      <div class="dishlist-container">
          <%= image_tag item.photo.url, class: "img-responsive img-rounded dish-image" unless item.photo.nil? %>
          <div class="dishlist-info-wrapper">
            <div class="dishlist-name"><%= item.name %></div>
            <div class="dishlist-price"><%= item.price.round %>€</div>
          </div>
          <%= link_to "", business_place_path(item.business_place), class: "dish-link" unless item.business_place.nil? %>
          <!-- <a class="dish-link" href="#" ></a> -->
      </div>
      <div class="dishdetails-container">
      <!-- <div style="display: flex; justify-content: space-between;">
        <div class="dishdetails-h1"><%= item.business_place.name %></div>
        <div><%= image_tag "icon_walk.svg" %> <span style="vertical-align: bottom;">10 min</span></div>
      </div> -->
            <div class="dishdetails-h1"><%= item.business_place.name %></div>
            <!-- <div class="dishdetails-h2"><%= item.business_place.cuisine.name %></div> -->
            <div>
            <% unless session[:lat].blank? and session[:lng].blank? %>
              <!-- You should render this as a partial html.erb if you want to dynamic change the colors and apply hover and etc -->
              <%#= render 'shared/icons/icon_walk' %>

              <!-- SVG as an image - You lose the dynamic changes you can do in a vector when you do like this. But we will do anyway because of lack of time -->
              <%= image_tag "icon_walk.svg" %>

              <span style="vertical-align: bottom;">
              <% time_format = "%_M min" #23min %>
              <% time_format = "%k h %_M min" if item.walking_time.round > 60 #5h 23 min %>
              <%= Time.at(item.walking_time.round * 60).utc.strftime(time_format) %>
              </span>
            <% end %>
            </div>
            <!-- <div class="dishdetails-p"><%#= item.business_place.cuisine.name %></div> -->
      </div>


<!-- 'https://static.pexels.com/photos/128388/pexels-photo-128388.jpeg' -->

app/views/shared/_modal_login.html.erb
  <!-- Modal Login -->
  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <%- if devise_mapping.omniauthable? %>
            <%- resource_class.omniauth_providers.each do |provider| %>
              <%= link_to omniauth_authorize_path(resource_name, provider), class: "btn icon-btn btn-block signup-login-form__btn-xl btn-large space-1 btn-facebook btn-facebook-fresh js-facebook-auth" do %>
                <span class="icon-container">
                  <i class="fa fa-facebook"></i>
                </span>
                <span class="text-container">
                  <%= "Log in with #{OmniAuth::Utils.camelize(provider)}" %>
                </span>
              <% end %>
            <% end -%>
          <% end -%>
          <div class="text-center">or</div>
          <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <%# simple_form_for(:user, :url => user_session_path) do |f| %>
          <div class="form-inputs">
            <%= f.input :email, required: false, autofocus: true %>
            <%= f.input :password, required: false %>
            <div class="flex-wrapper-sp-between">
              <div>
                <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
              </div>
              <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
              <div>
                <%= link_to "Forgot your password?", new_password_path(resource_name) %>
              </div>
              <% end -%>
            </div>
          </div>
          <%= f.button :submit, "Log in", class: "btn icon-btn btn-block signup-login-form__btn-xl btn-large space-1 btn-signup-yellow"%>

            <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
            <hr>
            <div class="flex-wrapper-sp-between">
              <div>
                <span>Don't have an account?</span>
              </div>
              <div>
                <%= link_to "Sign up", "#", class: "btn-medium btn-medium-sm", data: { dismiss: "modal", toggle: "modal", target: "#signUpModal" } %>
              </div>
            </div>
            <% end -%>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_modal_signup.html.erb
<!-- Modal Sign Up -->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <%- if devise_mapping.omniauthable? %>
            <%- resource_class.omniauth_providers.each do |provider| %>
              <%= link_to omniauth_authorize_path(resource_name, provider), class: "btn icon-btn btn-block signup-login-form__btn-xl btn-large space-1 btn-facebook btn-facebook-fresh" do %>
                <span class="icon-container">
                  <i class="fa fa-facebook"></i>
                </span>
                <span class="text-container">
                  <%= "Sign up with #{OmniAuth::Utils.camelize(provider)}" %>
                </span>
              <% end %>
            <% end -%>
          <% end -%>
          <div class="text-center">or</div>
          <br>
          <%= link_to new_registration_path(resource_name), class: "btn icon-btn btn-block signup-login-form__btn-xl btn-large space-1 btn-signup-yellow" do %>
                <span class="text-container">
                  <%= "Sign up with email" %>
                </span>
          <% end %>
          <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
            <hr>
            <div class="flex-wrapper-sp-between">
              <div>
                <span>Already a Fresh member?</span>
              </div>
              <div>
                <%= link_to "Log in", "#", class: "btn-medium btn-medium-sm", data: { dismiss: "modal", toggle: "modal", target: "#loginModal" } %>
              </div>
            </div>
          <% end -%>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<% unless user_signed_in? %>
  <%= render "shared/modal_signup" %>
  <%= render "shared/modal_login" %>
<% end %>

<div class="navbar-wagon navbar-wagon-fixed">
<!-- Logo -->
<%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", class: "desktop" %>
  <%= image_tag "logo_f.png", class: "mobile" %>
<% end %>


  <!-- Search form -->
<!--     <form action="/items/search" class="navbar-wagon-search">
      <input type="hidden" name="location" value="<%= "Lisboa" if @city.blank? %> <%= @city unless @city.blank? %>">
      <input type="text" name="query" class="navbar-wagon-search-input" placeholder="What do you want to eat today?">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? && current_user.business_places.include?(@business_place) && current_page?(controller: 'business_places', action: 'show')%>
      <%#= link_to "Manage #{@business_place.name}", "#", class:"navbar-wagon-link", data: { toggle: "modal", target: "#manage-bp-modal"} %>
      <div class="dropdown">
      <%= link_to "Manage #{@business_place.name}", "#", class: "navbar-wagon-link dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
            <%= link_to "#", data: { dismiss: "modal", toggle: "modal", target: "#edit-bp"} do %>
            <i class="fa fa-list-alt" aria-hidden="true"></i>
            <span>&nbsp; Edit Basic Info</span>
            <% end %>
            <hr class="no-padding">
            <%= link_to "#", data: { dismiss: "modal", toggle: "modal", target: "#manage-dishes-modal"} do %>
            <i class="fa fa-spoon" aria-hidden="true"></i>
            <span>&nbsp; Manage Dishes</span>
            <% end %>
        </li>
      </ul>
      </div>
    <% end %>

    <% if user_signed_in? %>


    <!-- Different navigation if login or not -->
    <%# if user_signed_in? %>

    <!-- Dishes Portifolio Link -->
    <%#= link_to "Manage Dishes", "#", class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#manage-dishes-modal"} %>

    <!-- Manage Colaborators -->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Add Members</a> -->

    <!-- Add your Business Link for Already Owners -->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Add new Business</a> -->

      <% if user_signed_in? && current_user.business_places.include?(@business_place) && current_page?(controller: 'business_places', action: 'show')%>
        <%= link_to "Add your Business", new_business_place_path , class: "navbar-wagon-link" %>
      <% else %>
        <div class="navbar-wagon-item">
        <%= link_to "Add your Business", new_business_place_path , class: "btn-medium btn-medium-sm" %>
        </div>
      <% end %>
<!--     <div class="navbar-wagon-item">
      <div class="dropdown">
      <a href="#" class="navbar-wagon-item navbar-wagon-link dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">Test Dropdown</a>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div> -->

    <!-- Notification -->
    <%# link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
    <!-- <div class="badge-container">
      <i class="fa fa-envelope-o"></i>
      <div class="badge badge-blue">3</div>
    </div> -->
    <%# end %>

    <!-- Profile picture and dropdown -->
<!--     <div class="nav-bar-wagon-item">
      <%# current_user.first_name %>
    </div> -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%# raise %>
        <% if user_signed_in? && current_user.photo.url %>
          <%= image_tag current_user.photo.url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% elsif user_signed_in? && current_user.facebook_picture_url %>
          <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <hr class="no-padding">
          <% unless current_user.business_places.empty? %>
            <% current_user.business_places.each do |bp| %>
              <li>
                <%= link_to business_place_path(bp), class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="fa fa-cutlery" aria-hidden="true"></i> <%= bp.name %>
              <% end %>
              </li>
            <% end %>
          <!-- <li>
          <%#= link_to "/business_places/#{current_user.business_places.last.id}", class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-cog"></i> Manage Business Places
          <%# end %>
          </li> -->
          <% end %>
          <hr class="no-padding">
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Signup text link -->
    <%# link_to t(".sign_up", default: "Sign up"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#loginModal" } %>

    <%= link_to "Add your Business", "#" , class: "btn-medium btn-medium-sm", data: { toggle: "modal", target: "#loginModal" } %>

    <%= link_to "Sign up", "#" , class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#signUpModal" } %>

    <%= link_to "Login", "#" , class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#loginModal" } %>

    <!-- Login text link -->
    <%# link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <!--     <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars fa-2x dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <% if user_signed_in? %>
        <li>
          <%= link_to edit_user_registration_path(current_user) do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <hr class="no-padding">
        <li>
          <% if user_signed_in? && current_user.business_places.include?(@business_place) && current_page?(controller: 'business_places', action: 'show')%>
                <li><%= link_to "Manage #{@business_place.name}", "#", data: { toggle: "modal", target: "#manage-bp-modal"} %></li>
                <% end %>
        </li>
        <hr class="no-padding">
        <li>
          <%= link_to new_business_place_path , class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-plus"></i> Add new Business
          <% end %>
        </li>
        <hr class="no-padding">
        <% unless current_user.business_places.empty? %>
          <% current_user.business_places.each do |bp| %>
              <li>
                <%= link_to business_place_path(bp), class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="fa fa-cutlery" aria-hidden="true"></i> <%= bp.name %>
                <% end %>
              </li>
          <% end %>
        <% end %>
        <hr class="no-padding">
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      <% else %>
        <li><%= link_to "Add your Business", "#" , class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#loginModal" } %></li>
        <li><%= link_to "Sign up", "#" , class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#signUpModal" } %></li>
        <li><%= link_to "Login", "#" , class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#loginModal" } %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>