config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  get "pages/about" => "pages#about", as: :about_page

  get "/location" => "application#location"

  resources :cuisines, only: [:new, :create]

  resources :ingredients, only: [:new, :create]

  get "business_places/owned" => "business_places#owned", as: :owned_business_places

  resources :business_places do
    resources :dishes, only: [:create, :edit, :update]
    resources :items, only: [:new, :create, :edit, :update]
  end

  post "items/copy" => "items#copy", as: :copy_items

  resources :dishes, only: [:destroy]
  resources :items, only: [:destroy]

  get "items/search" => "items#search", as: :search_items

  resources :roles, except: [:index, :show]

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :business_place
  has_many :items

  validates :name, length: { minimum: 3, maximum: 30 }
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, uniqueness: { scope: [:business_place] }
  validates :business_place, presence: true
  validates :description, presence: true
  validates :price, presence: true

  def today_items
    self.items.where('start_datetime >= :start AND end_datetime <= :end', start: Date.today, end: Date.today + 1)
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  layout :resolve_layout

  before_action :set_dish, only: [:edit, :update, :destroy]

  def edit
    @business_place = BusinessPlace.find(params[:business_place_id])
    redirect_unauthorized_user
    @dish = Dish.find(params[:id])
  end

  def update
    @business_place = BusinessPlace.find(params[:business_place_id])

    redirect_unauthorized_user

    if @dish.update(dish_params)

      # Also update all today's items for this dish
      @dish.today_items.each do |item|
        item.name = @dish.name
        item.description = @dish.description
        item.price = @dish.price
        item.remote_photo_url = @dish.photo_url
        item.save
      end

      respond_to do |format|
        format.html { redirect_to business_place_path(@business_place) }
        format.js  { render :edit }
      end
    else
      respond_to do |format|
        format.html { redirect_to business_place_path(@business_place) }
        format.js  { render :edit }
      end
    end
  end

  def destroy
    @business_place = @dish.business_place
    redirect_unauthorized_user

    # Delete instead of destroy because we don't want
    # the callbacks to be called (we want items to still be available)
    # and not destroied together with the dish
    @dish.delete

    # Destroy also is there is any item in the day
    # with the destroied dish, get the ids in @today_destroied_items
    # to send in ajax and remove with animation
    @destroied_item_ids = @dish.business_place.today_items.where(dish: @dish).distinct.pluck(:id)
    @dish.business_place.today_items.where(dish: @dish).each do |i|
      i.destroy
    end

    flash[:success] = "Dish deleted"
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.js
    end
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :price, :description, :photo, :photo_cache)
  end

  def redirect_unauthorized_user
    #@business_place.users.include?(current_user)
    unless current_user.business_places.include?(@business_place)
      flash[:alert] = "You don't have access change to this Business Place"
      redirect_to business_place_path(@business_place)
    end
  end

  def set_dish
    @dish = Dish.find(params[:id])
  end

  def resolve_layout
    case action_name
    when "edit"
      "modal"
    else
      "application"
    end
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= simple_form_for [@business_place, @dish], remote: true do |f| %>
<div class="form-row-inline">
  <span class="label-inline">Name</span>
  <div>
  <%= f.input :name, label: false, placeholder: "Dish's name" %>
  </div>
</div>
<div class="form-row-inline">
  <span class="label-inline">Description</span>
  <div>
  <%= f.input :description, label: false, placeholder: "Description" %>
  </div>
</div>
<div class="form-row-inline">
  <span class="label-inline">Price</span>
  <div>
  <%= f.input :price, label: false, placeholder: "Price" %>
  </div>
</div>
<div class="form-row-inline">
  <span class="label-inline">Photo</span>
  <div>
  <%= f.input :photo, label: false %>
  <%= f.input :photo_cache, as: :hidden %>
  <div class="input-file-feedback">
      <span class="label-inline">&nbsp;</span>
      <span id="dishUploadFile"></span>
  </div>
  <!-- Placeholder space for the layout not to break -->
  <span id="space-holder">&nbsp;</span>
  </div>
</div>
  <hr style="margin-top: 15px; margin-bottom: 15px;">
  <div style="display: flex; justify-content: space-between;">
    <div>
      <%= link_to "Delete", dish_path(@dish), class: "btn btn-medium", method: :delete, remote: true %>
    </div>
    <div>
      <button type="button" class="btn btn-medium" data-dismiss="modal" aria-label="Close">Cancel</button>
      <%= f.button :submit, class: "btn btn-medium btn-medium-yellow", value: "Save", id: "dish-edit-save" %>
    </div>
  </div>
<% end %>


<%= content_for(:after_js) do %>
  <script>
    // To change the display of the button after selection
    $("#dish_photo").change(function () {
        // Fix layout bug
        $("#space-holder").hide();
        $("#dishUploadFile").text("1 photo selected");
    });
  </script>
<% end %>

app/views/dishes/destroy.js.erb
$(function () {
   // Disable modal - Do not work on IOS Safari
   $('#edit-dish-modal').modal('hide');

   // Disable Modal - IOS Safari - DON'T WORK YET!!!!
   $('body').removeClass('modal-open');
   $('.modal-backdrop').remove();
});

$('#dish-id-<%= @dish.id%>').hide();

<% @destroied_item_ids.each do |item_id| %>
  $('#item-id-<%= item_id %>').slideUp();
<% end %>

//Hide item from the modal list
//$('a[data-id=<%= @dish.id %>]').hide();

app/views/dishes/edit.html.erb
<%= render 'form' %>
<%= content_for(:modal_title) do %>
Edit this dish
<% end %>

app/views/dishes/edit.js.erb
// Here you will write *javascript* that would be executed by the browser
<% if @dish.errors.any? %>
  // Render new review form with errors
  $('#edit_dish_<%= @dish.id%>').html("<%= j render 'dishes/form', business_place: @business_place, dish: @dish %>");
<% else %>

 // Disable modal
 $('#edit-dish-modal').modal('hide');

 // Update view if there is items using this changed dish

 // Remove all items of the day with same changed dish
 $('div[dish-id=<%= @dish.id %>]').remove();

 // Append html elements of the changed items as hidden
 <% @dish.today_items.each do |i| %>
   var newItem<%= i.id %> = $("<%= j render '/business_places/item_show', item: i %>").hide();
    $('.js-items-list').append(newItem<%= i.id %>);
 <% end %>

 // Animate to show these items
 // Set animation to happen after modal hide
 $('#edit-dish-modal').on('hidden.bs.modal', function (e) {
    // after modal hide animation execute this
    // Show the new item with slideDown
    <% @dish.today_items.each do |i| %>
      newItem<%= i.id %>.slideDown("slow");
    <% end %>
  });

<% end %>