config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  get "pages/about" => "pages#about", as: :about_page

  get "/location" => "application#location"

  resources :cuisines, only: [:new, :create]

  resources :ingredients, only: [:new, :create]

  get "business_places/owned" => "business_places#owned", as: :owned_business_places

  resources :business_places do
    resources :dishes, only: [:create, :edit, :update]
    resources :items, only: [:new, :create, :edit, :update]
  end

  post "items/copy" => "items#copy", as: :copy_items

  resources :dishes, only: [:destroy]
  resources :items, only: [:destroy]

  get "items/search" => "items#search", as: :search_items

  resources :roles, except: [:index, :show]

end

app/models/business_place.rb
class BusinessPlace < ActiveRecord::Base
  has_many :business_cuisines, dependent: :destroy
  belongs_to :cuisine
  has_many :cuisines, through: :business_cuisines
  has_many :business_place_users, dependent: :destroy
  has_many :users, through: :business_place_users
  has_many :dishes, dependent: :destroy
  has_many :items, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: [:address, :city] }
  validates :description, presence: true, length: { maximum: 35 }
  validates :address, presence: true
  validates :zip_code, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :phone_number, presence: true
  validates :cuisine, presence: true
  # validates :latitude, presence: true
  # validates :longitude, presence: true
  mount_uploader :cover_photo, PhotoUploader
  accepts_nested_attributes_for :cuisines

  geocoded_by :full_address
  after_validation :geocode, if: :full_address_changed?
  after_create :create_business_place_user

  attr_accessor :current_user

  def show_address
    "#{address}, #{city}"
  end

  def full_address
    "#{address}, #{zip_code} #{city} #{ISO3166::Country[country].name}"
  end

  def full_address_changed?
    address_changed? || zip_code_changed? || city_changed? || country_changed?
  end

  def create_business_place_user
    bpu = BusinessPlaceUser.new(business_place: self, user: current_user, main: true)
    bpu.save
  end

  def owner
    bpu = BusinessPlaceUser.where(business_place: self, main: true).first
    return bpu.user unless bpu.nil?
    return nil
  end

  def today_items
    self.items.where('start_datetime <= :start AND end_datetime >= :end', start: Date.today, end: Date.today + 1)
  end
end

app/controllers/business_places_controller.rb
class BusinessPlacesController < ApplicationController
  before_action :set_business_place, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @business_places = BusinessPlace.all
  end

  def new
    @business_place = BusinessPlace.new
    @cuisines = Cuisine.all
  end

  def show
    # Find only the dishes of today to show
    @items = @business_place.today_items

    # Prepare previous dishes for the modal new item view
    @dishes = @business_place.dishes.where(status: "active")

    # Prepare for edit dish modal form
    @dish = @business_place.dishes.new

    # This logic is because we don't have a Dishes Table
    # distinct_names = Item.where(business_place_id: @business_place.id).distinct.pluck(:name)
    # @previous_items = []
    # distinct_names.each do |n|
    #   @previous_items << @business_place.items.find_by_name(n)
    # end

    # This is for the Edit Business Place to show combo-box of Cuisines
    @cuisines = Cuisine.all

    # Prepare to show the modal simple form for of the New Dish
    @item = Item.new
    @item.business_place = @business_place

    # To use for facebook share
    if params[:item]
      @show_item = Item.find(params[:item])
    end

  end

  def create
    @business_place = BusinessPlace.new(business_place_params)
    @business_place.current_user = current_user
    # "cuisines"=>"2", "cuisine_ids"=>["1", "3", ""]}
    # params { business_place: { address: "", cuisines: "2", cuisine_ids }}
    # @business_place.cuisine = Cuisine.find(params[:business_place][:cuisines])
    if @business_place.save
      redirect_to business_place_path(@business_place)
    else
      render :new
    end
  end

  def edit
    redirect_unauthorized_user
    @cuisines = Cuisine.all
    # @cuisine_id = 1
    # unless @business_place.business_cuisines.where(main: true).empty?
    #   @cuisine_id = @business_place.business_cuisines.where(main: true).first.cuisine_id
    # end

  end

  def update
    redirect_unauthorized_user
    #@business_place.cuisine = Cuisine.find(params[:business_place][:cuisines])
    if @business_place.update(business_place_params)
      redirect_to business_place_path(@business_place)
    else
      render :edit
    end
  end

  def owned
    @business_places = current_user.business_places
  end

  def destroy
    redirect_unauthorized_user

    @business_place.destroy
    flash[:success] = "Business place deleted"
    redirect_to request.referer
  end

  private

  def business_place_params
    params.require(:business_place).permit(:address, :city, :country, :zip_code,
                   :name, :opening_time, :cover_photo, :average_cost, :phone_number,
                   :latitude, :longitude, :description, :cuisine_id, cuisine_ids: [])
  end

  def set_business_place
    @business_place = BusinessPlace.find(params[:id])
  end

  def redirect_unauthorized_user
    unless current_user.business_places.include?(@business_place)
      flash[:alert] = "You don't have access change to this Business Place"
      redirect_to business_place_path(@business_place)
    end
  end
end

app/helpers/business_places_helper.rb
module BusinessPlacesHelper
end

app/views/business_places/_form.html.erb
<%= simple_form_for @business_place do |f| %>

<div class="form-row-inline">
  <span class="label-inline">Name</span>
  <div>
    <%= f.input :name, label: false, placeholder: "Enter the name" %>

  </div>
</div>

<div class="form-row-inline">
  <span class="label-inline">Description</span>
  <div>
    <%= f.input :description, label: false, placeholder: "Enter a punch line description" %>
  </div>
</div>

<div class="form-row-inline">
  <span class="label-inline">Cuisine</span>
  <div>
    <%= f.input :cuisine_id, label: false, collection: @cuisines, prompt: "Select the main cuisine" %>
    <%# f.input :cuisine_id, collection: @cuisines, selected: @business_place.cuisine.id, prompt: "Select the main cuisine", label: "Main cuisine" %>
    <%#= f.association :cuisines, as: :check_boxes, label: "What other cuisines does it have?" %>
  </div>
</div>

<div class="form-row-inline">
  <span class="label-inline">Phone</span>
  <div>
    <%= f.input :phone_number, label: false, placeholder: "Enter the Phone Number" %>
  </div>
</div>

<div class="form-row-inline">
  <span class="label-inline">Address</span>
  <div>
    <%= f.input :address, label: false %>
    <%#= f.input :average_cost, placeholder: "Enter the average cost e.g. 30 euros for 2 people", label: "Cost" %>
    <%#= f.input :opening_time, placeholder: "Enter working time e.g. 12pm - 9pm", label: "Opening Time" %>
  </div>
</div>

<div class="form-row-inline">
  <span class="label-inline">Zip code</span>
  <div>
    <%= f.input :zip_code, label: false %>
  </div>
</div>

<div class="form-row-inline">
  <span class="label-inline">City</span>
  <div>
    <%= f.input :city, label: false %>
  </div>
</div>

<div class="form-row-inline">
  <span class="label-inline">Country</span>
  <div>
    <%= f.input :country, label: false, priority: [ 'PT' ] %>
  </div>
</div>


  <span class="label-inline">Cover</span>
  <div>
    <%= f.input_field :cover_photo, label: false %>
    <div class="input-file-feedback">
      <span class="label-inline">&nbsp;</span>
      <span id="businessPlaceUploadFile"></span>
    </div>
    <%= f.input :cover_photo_cache, as: :hidden %>
  </div>


<%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

<%= content_for(:after_js) do %>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyANIX5OkPPRTJZkKRUF80Nso8xQvwEY2mE"></script>


<script>
  // To change the display of the button after selection
  $("#business_place_cover_photo").change(function () {
      $("#businessPlaceUploadFile").text("1 photo selected");
  });
</script>

<% end %>

app/views/business_places/_item_show.html.erb
<div class="wrapper-lightgrey" id="item-id-<%= item.id %>" dish-id="<%= item.dish.id unless item.dish.nil? %>">
<a name="item-anchor-<%= item.id %>"></a>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div class="dish-show-container">
          <%= image_tag  item.photo.url, class: "img-responsive img-rounded dish-image" %>
        </div>
        </div>
        <div class="col-sm-6">
          <div class="dish-show-container">
          <% if (user_signed_in? and current_user.business_places.include?(@business_place)) or @close_button %>
            <%= link_to item_path(item), method: :delete, remote: true, class: "close close-lg", aria: { label: "Close" } do %>
              <span aria-hidden="true">&times;</span>
            <% end %>
          <% end %>
          <a name="item-id-<%= item.id %>"></a>
          <div class="dish-name"><%= item.name %></div>
          <div class="dish-price">Price: <%= item.price.round %>€</div>
          <div class="dish-description"><%= item.description %></div>
          <div class="share-social"><i class="fa fa-share" aria-hidden="true"><span style="font-family: 'Open Sans', 'Helvetica', 'sans-serif'"> share</span></i></div>
          <div class="dish-social">
            <%= social_share_button_tag("The #{item.name} served at #{@business_place.name} today is looking good!", url: business_place_url(item.business_place) + "?item=#{item.id}" ) %>
            <%#= social_share_button_tag(@item.name, image: @item.photo.url, url: request.original_url + "#item-anchor-#{item.id}", desc: @business_place.name) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="height: 2px; background-color: white;"></div>

app/views/business_places/_manage_panel.html.erb
<!-- Link to Edit Business Place -->
  <div class="container col-sm-12">
    <div class="row">

      <div class="col-sm-6">
        <%= link_to "#", class: "task text-center", data: { dismiss: "modal", toggle: "modal", target: "#edit-bp"} do %>
            <div class="manage-icon">
              <i class="fa fa-list-alt fa-2x" aria-hidden="true"></i> &nbsp;
            </div>
            <span class="manage-link">Edit Basic Info</span>

        <% end %>
      </div>

      <div class="col-sm-6">
        <%= link_to "#", class: "task text-center", data: { dismiss: "modal", toggle: "modal", target: "#manage-dishes-modal"} do %>
            <i></i>
            <div class="manage-icon">
              <i class="fa fa-spoon fa-2x" aria-hidden="true"></i> &nbsp;
            </div>
            <span class="manage-link">Manage Dishes</span>

        <% end %>
      </div>


<!--       <div class="col-sm-4">
        <%#= link_to "#", class: "task text-center", data: { dismiss: "modal", toggle: "modal", target: "#manage-dishes-modal"} do %>
            <i></i>
            <div class="manage-icon">
              <i class="fa fa-user-plus fa-2x" aria-hidden="true"></i> &nbsp;
            </div>
            <span class="manage-link">Manage Users</span>

        <%# end %>
      </div> -->
    </div>
  </div>

app/views/business_places/_modal_edit_business_place.html.erb
<!-- Edit Business Place Modal -->
  <div class="modal fade" id="edit-bp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close close-md" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Edit Basic Info</h4>
        </div>
        <div class="modal-body">
           <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>

<%= content_for(:after_js) do %>

<% end %>

app/views/business_places/_modal_edit_dish.html.erb
<!-- Edit Dish Modal -->
<div class="modal fade" id="edit-dish-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    <!-- URL Page will be loaded here -->
    </div>
  </div>
</div>

app/views/business_places/_modal_manage_business_place.html.erb
<!-- Manage Business Place Modal -->
  <div class="modal fade" id="manage-bp-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close close-md" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Manage Business Place</h4>
        </div>
        <div class="modal-body">
           <%= render 'manage_panel' %>
        </div>
      </div>
    </div>
  </div>

app/views/business_places/_modal_manage_dishes.html.erb
<!-- Manage Dishes Modal -->

<div class="modal fade" id="manage-dishes-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <% unless @dishes.empty? %>
        <div class="modal-header">
          <button type="button" class="close close-md" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Select the dish to edit</h4>
        </div>
        <% end %>
        <div class="modal-body">
        <% unless @dishes.empty? %>
              <% @dishes.each do |d| %>
                <%# f.button :submit, value: i.id, style: "background-image: url(#{i.photo.url}) no-repeat;", class: "" %>
                <%= link_to "/business_places/#{@business_place.id}/dishes/#{d.id}/edit", class: "dish-manage-link", id: "dish-id-#{d.id}", data: { dismiss: "modal", toggle: "modal", target: "#edit-dish-modal", dish_id: d.id} do %>
                  <div class="cover-item" style="background-image: url('<%= d.photo.url %>')"></div>
                <% end %>
              <% end %>
        <% else %>
          <h4>You have no dishes yet</h4>
        <% end %>
        </div>
     <!--    <hr style="margin-left: 15px; margin-right: 15px; margin-top: 0px; margin-bottom: 0px;"> -->
        <div class="modal-footer">
        <%= link_to "Add Dish", "#", class: "btn btn-primary btn-block", data: { dismiss: "modal", toggle: "modal", target: "#add-dish-modal"} %>
        </div>
      </div>
    </div>
  </div>

app/views/business_places/destroy.html.erb
<h1>BusinessPlaces#destroy</h1>
<p>Find me in app/views/business_places/destroy.html.erb</p>

app/views/business_places/edit.html.erb
<div class="margin-top"></div>
<div class="container">
  <div class="row" <%= @cuisine_id %>>
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <h2>Edit your business:</h2>
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/business_places/map.html.erb
<h3>Get directions</h3>

<div>
  <form action="http://maps.google.com/maps" method="get" target="_blank">
    <input type="text" name="saddr" placeholder="Starting address" />
    <input type="hidden" name="daddr" value="<%= @business_place.full_address %>"/>
    <input type="submit" value="get directions" class= "btn btn-info"/>
  </form>
</div>

  <div id="map" style="width: 100%; height: 400px;"></div>

  <%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyANIX5OkPPRTJZkKRUF80Nso8xQvwEY2mE">
    console.log('google_api')
  </script>


  <script type="text/javascript">
    var myLatlng = new google.maps.LatLng(<%= @business_place.latitude %> , <%= @business_place.longitude %>);

    var myOptions = {
      zoom: 16,
      center: myLatlng,
      scrollwheel: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
  styles: [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"transit.station.bus","elementType":"geometry","stylers":[{"visibility":"on"},{"hue":"#ff0000"}]},{"featureType":"transit.station.bus","elementType":"geometry.fill","stylers":[{"visibility":"on"}]},{"featureType":"transit.station.bus","elementType":"labels.text","stylers":[{"visibility":"on"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#4690ec"},{"visibility":"on"}]},{"featureType":"water","elementType":"geometry","stylers":[{"visibility":"on"}]}] // TODO: replace [] by array from https://snazzymaps.com/
};

var map = new google.maps.Map(document.getElementById('map'), myOptions);
var marker = new google.maps.Marker({
  position: myLatlng,
  map: map,
  title: "You are here!"
});
</script>
<% end %>

app/views/business_places/new.html.erb
<div class="margin-top"></div>
<div class="wrapper-yellow text-center">
Add your business here
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <%= render 'form' %>
      <%#= simple_form_for @business_place do |f| %>
      <%#= f.input :address %>
      <%#= f.input :zip_code %>
      <%#= f.input :city %>
      <%#= f.input :country, priority: [ 'PT' ] %>
      <%#= f.input :name, placeholder: "Enter the name" %>
      <%#= f.input :phone_number, placeholder: "Enter the Phone Number" %>
      <%#= f.input :description, placeholder: "Enter a punch line description" %>
      <%#= f.input :average_cost, placeholder: "Enter the average cost e.g. 30 euros for 2 people", label: "Cost" %>
      <%#= f.input :opening_time, placeholder: "Enter working time e.g. 12pm - 9pm", label: "Opening Time" %>
      <%#= f.input :cover_photo %>
      <%#= f.input :cover_photo_cache, as: :hidden %>
      <%#= f.input :cuisines, collection: @cuisines, prompt: "Select the main cuisine", label: "Main cuisine" %>
      <%#= f.association :cuisines, as: :check_boxes, label: "What other cuisines does it have?" %>
      <%#= f.button :submit, class: "btn btn-primary btn-block" %>
      <%# end %>
    </div>
  </div>
</div>
<div class="wrapper-white"></div>

<%#= content_for(:after_js) do %>
  <!-- <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyANIX5OkPPRTJZkKRUF80Nso8xQvwEY2mE"></script> -->
<%# end %>

app/views/business_places/owned.html.erb
<%= link_to "New", new_business_place_path, class: "btn btn-primary" %>

<% @business_places.each do |x| %>
  <p> <%= link_to x.name, business_place_path(x) %> </p>
  <p><%= x.description %></p>
  <p><%= x.opening_time %></p>
  <p><%= x.address %></p>
  <p><%= x.city %></p>
  <p><%= x.country %></p>
  <p><%= x.zip_code %></p>
  <p><%= x.phone_number %></p>

  <%= link_to "Delete", business_place_path(x), class: "btn btn-primary", method: :delete,
                                  data: { confirm: "You sure?" } %>

  <%= link_to "Edit", edit_business_place_path(x), class: "btn btn-primary" %>
<% end %>

app/views/business_places/update.html.erb
<h1>BusinessPlaces#update</h1>
<p>Find me in app/views/business_places/update.html.erb</p>